Queue: Expose len and capacity for Consumer and Producer
japaric/heapless pull request #182
Opened 2020-11-03 09:00 UTC by almusil

This PR exposes `capacity` and `len` for The `Consumer` and `Producer` which were not available in either of those after split.

2020-11-03 10:17 UTC, korken89 requested changes
Thanks for the PR!

Could you update the documentation to say that these are conservative estimates?
There might be an interrupt in between the two reads that causes the following:

* For the `Producer` will see N free spots, but there might be more free space.
* For the `Consumer` it will see M queued items, but there may be more than M in the queue. 

Else it looks good!

2020-11-03 10:30 UTC, almusil commented
> Thanks for the PR!
> 
> Could you update the documentation to say that these are conservative estimates?
> There might be an interrupt in between the two reads that causes the following:
> 
>     * For the `Producer` will see N free spots, but there might be more free space.
> 
>     * For the `Consumer` it will see M queued items, but there may be more than M in the queue.
> 
> 
> Else it looks good!

Done, thank you.

2020-11-03 12:31 UTC, korken89 approved these changes
bors merge

2020-11-04 06:47 UTC, almusil commented
@korken89 Do you have an idea why it failed on x86 in `std`? I am kinda clueless. Only one thing that comes to my mind is some kind of regression in rustc/llvm?

2020-11-04 13:23 UTC, almusil commented
Local run of: `TSAN_OPTIONS="suppressions=$(pwd)/suppressions.txt" RUSTFLAGS="-Z sanitizer=thread" cargo test --test tsan --features x86-sync-pool --target x86_64-unknown-linux-gnu` works just fine

2020-11-04 14:40 UTC, korken89 commented
bors retry

2020-11-06 07:08 UTC, korken89 commented
I'm not sure what is wrong here, it's passing for me locally as well.

Ping @japaric, you added these checks do you see what is causing them to fail?

2020-11-30 07:04 UTC, almusil commented
Hello,

any updates on this please?
I would love to use heapless with this PR included instead of the fork.

2020-11-30 14:50 UTC, korken89 commented
bors retry

2020-11-30 14:54 UTC, korken89 commented
It seems that Travis has shutdown and we need to switch to GHA.
I'll manually merge for now.

2020-11-30 14:55 UTC, merged