Relax Vec bounds to allow for zero-length Vecs
japaric/heapless pull request #261
Opened 2021-12-28 19:16 UTC by haata

Use when building generated code where it's possible to have a zero
length array/vector (e.g. wire-format). See #252

- Added vec::tests::zero_capacity test
- Added sealed::greater_than_eq_0

2021-12-29 07:37 UTC, korken89 requested changes

2021-12-29 07:37 UTC, korken89 commented on src/vec.rs
> +        assert_eq!(v.as_slice(), &[]);
Please add the check for `is_empty` and `is_full`.

2021-12-29 20:03 UTC, haata commented
Added `is_full` and `is_empty` checks.

2021-12-30 15:08 UTC, korken89 approved these changes
bors merge

2022-01-10 07:26 UTC, merged